# Dependencies
markdown:         redcarpet
highlighter:      pygments

plugins:
  - jekyll-gist

# Permalinks
permalink:        pretty

# Setup
title:            Helen Zhou
tagline:          'MEng Student'
description:      'Hi! My name is Helen, and I am an M.Eng. student in MIT EECS and part of the Clinical Machine Learning Group at CSAIL/IMES. I am working with Prof. David Sontag on '
url:              http://helen-zhou.com
baseurl:          /

author:
  name:           'Helen Zhou'
  url:            https://github.com/hlzhou

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/hlzhou/hlzhou.github.io
