# Dependencies
markdown:         redcarpet
highlighter:      pygments

plugins:
  - jekyll-gist

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Permalinks
permalink:        pretty

# Setup
title:            Helen Zhou
tagline:          'MEng Student'
description:      'My name is Helen, and I am an M.Eng. student in MIT EECS. My research interests are machine learning, computer vision, and natural language processing.'
url:              http://helen-zhou.com
baseurl:          /

author:
  name:           'Helen Zhou'
  url:            https://github.com/hlzhou

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/hlzhou/hlzhou.github.io
